{% set name = "autowrap" %}
{% set version = "0.22.9" %}
{% set sha256 = "ddfccfc14203236079034239765a0e5234dc098ef20c2db4099c6ba99416d09a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autowrap = autowrap.Main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cython >=0.19

test:
  imports:
    - autowrap
    - autowrap.data_files
  commands:
    - autowrap --version

about:
  home: https://github.com/OpenMS/autowrap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generates Python Extension modules from commented Cython CXD files
  dev_url: https://github.com/OpenMS/autowrap

extra:
  recipe-maintainers:
    - aseyboldt
    - synapticarbors
    - jpfeuffer
    - timosachsenberg
