{% set name = "autowrap" %}
{% set version = "0.16.0" %}
{% set sha256 = "2caff987a4afb3b64217030119c3127aae97bda55d20dbc30182a7e11a1383ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - autowrap = autowrap.Main:main

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - cython >=0.19
  run:
    - python
    - setuptools
    - cython >=0.19

test:
  imports:
    - autowrap
    - autowrap.data_files
  commands:
    - autowrap --version

about:
  home: https://github.com/uweschmitt/autowrap
  license: BSD-3-Clause
  license_family: BSD
  # autowrap does not include its license file in the latest pypi release,
  # but will in the next release.  (TODO for next release)
  summary: 'Generates Python Extension modules from commented Cython CXD files'
  dev_url: https://github.com/uweschmitt/autowrap

extra:
  recipe-maintainers:
    - aseyboldt
