{% set name = "autowrap" %}
{% set version = "0.22.10" %}
{% set sha256 = "49d48294574b67884a650a68a24ab1775093fe2d624ff5e9950581f6694433fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autowrap = autowrap.Main:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cython >=0.19
    - setuptools

test:
  imports:
    - autowrap
    - autowrap.data_files
  requires:
    - pip
  commands:
    - autowrap --version
    - pip check

about:
  home: https://github.com/OpenMS/autowrap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generates Python Extension modules from commented Cython CXD files
  dev_url: https://github.com/OpenMS/autowrap

extra:
  recipe-maintainers:
    - aseyboldt
    - synapticarbors
    - jpfeuffer
    - timosachsenberg
