context:
  name: autowrap
  version: "0.24.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 87353a2e0b23de30dbcc93a339f2e52149dc918cda83d8f715255ef537d0fd93

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv
  python:
    entry_points:
      - autowrap = autowrap.Main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.03
    - pip
  run:
    - python >=${{ python_min }}
    - cython >=3.1
    - setuptools

tests:
  - python:
      imports:
        - autowrap
        - autowrap.data_files
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - autowrap --version

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Generates Python Extension modules from commented Cython CXD files
  homepage: https://github.com/OpenMS/autowrap
  repository: https://github.com/OpenMS/autowrap

extra:
  recipe-maintainers:
    - aseyboldt
    - synapticarbors
    - jpfeuffer
    - timosachsenberg
