appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DCOkV5YtflM3pacOsnSYAm/puWyOae/ay+uJi1McagPrRvO38K0xxBbjp8DeLFqylKE9KFfWRT41UWQ0jwx/R0z3KvBOfhOIP1VmqHaDCTw7J3zrX36alSNUd4G+WVApvXIirwAEtAOqHZfHwm5Wm1WG7hpx21OvAFoP2rRJEkLkbmk2C6lNUDGzNVGIEnmFWp8FpfFmGY4c0S8CUOjg9BXZKrixaXlKvLyIip3W822LzxMzqeq2PNVNsOiIuFCGYR0TBY3jt++rg1gvxtV6c0ZP3M9mGPjEIj2VIj6GlZq1YzUny9Rd5boj8wCZ9lYUHjZI+cmScXPVQL/QidCuejVTr1SUt8UQ9DjUcgRtb+uK3GP+e3DW5mOg7F2mhD4n5QIfYR/F3IyQ0Ka9wyzlFLCLKv/itp3t76ChACbAm6S+IyPnry9qqYI5IKdWvluaSu7ePqPdw8Odp8Ejqn4ucmpx5eg4U4ECPprUKpTrAtUeJyO7m0dTamc6U9h2mXRv6BPIIzRqgR1OkLptZyWabzy79+1NA4V31eGIsLgmBcdjhJLssr3qKl62B8OmRTKj5CuD2ZI0gPhEqZ0ZKzpIxxayfmXcc8+HgFQcTYLd7NTSWMSH3Sjp//fS+R/ILn8HlRNbZjY5d5gORtfTJ25YN8RQOEXZx2EYHMx03Ms/Prk=}
conda_forge_output_validation: false
